# Generated by Django 2.1 on 2018-08-24 13:35

from django.db import migrations, models
import src.brands.models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20180824_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, default='/brands/lmp.jpg', upload_to=src.brands.models.get_upload_path, verbose_name='Foto'),
        ),
    ]
