# Generated by Django 2.1 on 2018-08-23 15:57

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Frecuency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.CharField(blank=True, max_length=144)),
                ('monday', models.CharField(blank=True, max_length=144)),
                ('tuesday', models.CharField(blank=True, max_length=144)),
                ('wednesday', models.CharField(blank=True, max_length=144)),
                ('thursday', models.CharField(blank=True, max_length=144)),
                ('friday', models.CharField(blank=True, max_length=144)),
                ('saturday', models.CharField(blank=True, max_length=144)),
                ('sunday', models.CharField(blank=True, max_length=144)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frecuencia de visita',
                'verbose_name_plural': 'Frecuencia de visitas',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, verbose_name='Nombre de contacto')),
                ('subject', ckeditor.fields.RichTextField(blank=True, verbose_name='Asunto')),
                ('email', models.CharField(blank=True, max_length=144, verbose_name='Direción email')),
                ('message', ckeditor.fields.RichTextField(blank=True, verbose_name='Mensaje')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ultima actualización')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=144, verbose_name='Codigo de usuario')),
                ('avatar', models.ImageField(blank=True, default='/profile/avatar.png', null=True, upload_to=src.users.models.get_upload_path, verbose_name='Avatar de usuario')),
                ('bio', ckeditor.fields.RichTextField(blank=True, verbose_name='Biografia')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción')),
                ('phone', models.CharField(blank=True, max_length=144, verbose_name='Numero de teléfono')),
                ('country', models.CharField(choices=[('AFG', 'Afganistán'), ('ALA', 'Islas de Åland'), ('ALB', 'Albania'), ('DZA', 'Argelia'), ('ASM', 'Samoa Americana'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('AIA', 'Anguila'), ('ATA', 'Antártida'), ('ATG', 'Antigua y Barbuda'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ABW', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaiyán'), ('BHS', 'Bahamas'), ('BHR', 'Baréin'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BLR', 'Bielorrusia'), ('BEL', 'Bélgica'), ('BLZ', 'Belice'), ('BEN', 'Benín'), ('BMU', 'Bermuda'), ('BTN', 'Bután'), ('BOL', 'Bolivia'), ('BES', 'Bonaire, San Eustaquio y Saba'), ('BIH', 'Bosnia y Herzegovina'), ('BWA', 'Botsuana'), ('BVT', 'Isla Bouvet'), ('BRA', 'Brasil'), ('IOT', 'Territorio Británico del Océano Índico'), ('VGB', 'Islas Vírgenes Británicas'), ('BRN', 'Brunei'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('KHM', 'Camboya'), ('CMR', 'Camerún'), ('CAN', 'Canadá'), ('CPV', 'Cabo Verde'), ('CYM', 'Islas Caimán'), ('CAF', 'República de África Central'), ('TCD', 'Chad'), ('CHL', 'Chile'), ('CHN', 'China'), ('CXR', 'Isla de Pascua'), ('CCK', 'Islas Cocos'), ('COL', 'Colombia'), ('COM', 'Comoras'), ('COK', 'Islas Cook'), ('CRI', 'Costa Rica'), ('HRV', 'Croacia'), ('CUB', 'Cuba'), ('CUW', 'Curazao'), ('CYP', 'Chipre'), ('CZE', 'República Checa'), ('COD', 'República Democrática del Congo'), ('DNK', 'Dinamarca'), ('DJI', 'Yibuti'), ('DMA', 'Dominica'), ('DOM', 'República Dominicana'), ('TLS', 'Timor Oriental'), ('ECU', 'Ecuador'), ('EGY', 'Egipto'), ('SLV', 'El Salvador'), ('GNQ', 'Guinea Ecuatorial'), ('ERI', 'Eritrea'), ('EST', 'Estonia'), ('ETH', 'Etiopía'), ('FLK', 'Islas Malvinas'), ('FRO', 'Islas Faroe'), ('FJI', 'Fiji'), ('FIN', 'Finlandia'), ('FRA', 'Francia'), ('GUF', 'Guayana Francesa'), ('PYF', 'Polinesia Francesa'), ('ATF', 'Territorios del sur Franceses'), ('GAB', 'Gabón'), ('GMB', 'Gambia'), ('GEO', 'Georgia'), ('DEU', 'Alemania'), ('GHA', 'Ghana'), ('GIB', 'Gibraltar'), ('GRC', 'Grecia'), ('GRL', 'Groenlandia'), ('GRD', 'Granada'), ('GLP', 'Guadalupe'), ('GUM', 'Guam'), ('GTM', 'Guatemala'), ('GGY', 'Guernsey'), ('GIN', 'Guinea'), ('GNB', 'Guinea Bissau'), ('GUY', 'Guyana'), ('HTI', 'Haití'), ('HMD', 'Islas Heard y McDonald'), ('HND', 'Honduras'), ('HKG', 'Hong Kong'), ('HUN', 'Hungría'), ('ISL', 'Islandia'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Irán'), ('IRQ', 'Irak'), ('IRL', 'Irlanda'), ('IMN', 'Isla de Man'), ('ISR', 'Israel'), ('ITA', 'Italia'), ('CIV', 'Costa de Marfil'), ('JAM', 'Jamaica'), ('JPN', 'Japón'), ('JEY', 'Jersey'), ('JOR', 'Jordania'), ('KAZ', 'Kazajistán'), ('KEN', 'Kenia'), ('KIR', 'Kiribati'), ('XKX', 'Kosovo'), ('KWT', 'Kuwait'), ('KGZ', 'Kirguistán'), ('LAO', 'Laos'), ('LVA', 'Letonia'), ('LBN', 'Líbano'), ('LSO', 'Lesoto'), ('LBR', 'Liberia'), ('LBY', 'Libia'), ('LIE', 'Liechtenstein'), ('LTU', 'Lituania'), ('LUX', 'Luxemburgo'), ('MAC', 'Macao'), ('MKD', 'Macedonia'), ('MDG', 'Madagascar'), ('MWI', 'Malaui'), ('MYS', 'Malasia'), ('MDV', 'Maldivas'), ('MLI', 'Malí'), ('MLT', 'Malta'), ('MHL', 'Islas Marshall'), ('MTQ', 'Martinica'), ('MRT', 'Mauritania'), ('MUS', 'Mauricio'), ('MYT', 'Mayotte'), ('MEX', 'México'), ('FSM', 'Micronesia'), ('MDA', 'Moldavia'), ('MCO', 'Mónaco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MSR', 'Montserrat'), ('MAR', 'Marruecos'), ('MOZ', 'Mozambique'), ('MMR', 'Myanmar'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('NPL', 'Nepal'), ('NLD', 'Países Bajos'), ('ANT', 'Antillas Holandesas'), ('NCL', 'Nueva Caledonia'), ('NZL', 'Nueva Zelanda'), ('NIC', 'Nicaragua'), ('NER', 'Níger'), ('NGA', 'Nigeria'), ('NIU', 'Niue'), ('NFK', 'Isla Norfolk'), ('PRK', 'Corea del Norte'), ('MNP', 'Islas Marianas del Norte'), ('NOR', 'Noruega'), ('OMN', 'Omán'), ('PAK', 'Pakistán'), ('PLW', 'Palaos'), ('PSE', 'Territorios Palestinos'), ('PAN', 'Panamá'), ('PNG', 'Papúa Nueva Guinea'), ('PRY', 'Paraguay'), ('PER', 'Perú'), ('PHL', 'Filipinas'), ('PCN', 'Islas Pitcairn'), ('POL', 'Polonia'), ('PRT', 'Portugal'), ('PRI', 'Puerto Rico'), ('QAT', 'Catar'), ('COG', 'República del Congo'), ('REU', 'Reunión'), ('ROU', 'Rumanía'), ('RUS', 'Rusia'), ('RWA', 'Ruanda'), ('BLM', 'San Bartolomé'), ('SHN', 'Santa Elena'), ('KNA', 'San Cristóbal y Nieves'), ('LCA', 'Santa Lucía'), ('MAF', 'San Martín'), ('SPM', 'San Pedro y Miguelón'), ('VCT', 'San Vicente y las Granadinas'), ('WSM', 'Samoa Occidental'), ('SMR', 'San Marino'), ('STP', 'Santo Tomé y Príncipe'), ('SAU', 'Arabia Saudita'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SCG', 'Serbia y Montenegro'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leona'), ('SGP', 'Singapur'), ('SXM', 'San Martín'), ('SVK', 'Eslovaquia'), ('SVN', 'Eslovenia'), ('SLB', 'Islas Salomón'), ('SOM', 'Somalia'), ('ZAF', 'Sudáfrica'), ('SGS', 'Islas Georgia del Sur y Sandwich del Sur'), ('KOR', 'Corea del Sur'), ('SSD', 'Sudán del Sur'), ('ESP', 'España'), ('LKA', 'Sri Lanka'), ('SDN', 'Sudán'), ('SUR', 'Surinam'), ('SJM', 'Islas Svalbard y Jan Mayen'), ('SWZ', 'Suazilandia'), ('SWE', 'Suecia'), ('CHE', 'Suiza'), ('SYR', 'Siria'), ('TWN', 'Taiwán'), ('TJK', 'Tayikistán'), ('TZA', 'Tanzania'), ('THA', 'Tailandia'), ('TGO', 'República Togolesa'), ('TKL', 'Islas Tokelau'), ('TON', 'Tonga'), ('TTO', 'Trinidad y Tobago'), ('TUN', 'Túnez'), ('TUR', 'Turquía'), ('TKM', 'Turkmenistán'), ('TCA', 'Islas Turcos y Caicos'), ('TUV', 'Tuvalu'), ('VIR', 'Islas Vírgenes de los EE.UU.'), ('UGA', 'Uganda'), ('UKR', 'Ucrania'), ('ARE', 'Emiratos Árabes Unidos'), ('GBR', 'Reino Unido'), ('USA', 'Estados Unidos (USA)'), ('UMI', 'Islas menores alejadas de los Estados Unidos'), ('URY', 'Uruguay'), ('UZB', 'Uzbekistán'), ('VUT', 'Vanuatu'), ('VAT', 'Vaticano'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('WLF', 'Wallis y Futuna'), ('ESH', 'Sahara Occidental'), ('YEM', 'Yemen'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabue')], default='PAN', max_length=3, verbose_name='Pais')),
                ('city', models.CharField(blank=True, max_length=144, verbose_name='Ciudad')),
                ('direction1', ckeditor.fields.RichTextField(blank=True, verbose_name='Dirección 1')),
                ('direction2', ckeditor.fields.RichTextField(blank=True, verbose_name='Dirección 2')),
                ('zip_code', models.CharField(blank=True, max_length=144, verbose_name='Codigo zip')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='Miembro desde')),
                ('saldo', models.CharField(blank=True, max_length=144, verbose_name='Saldo disponible')),
                ('max_credit', models.CharField(blank=True, max_length=144, verbose_name='Credito maximo')),
                ('payment_lapse', models.CharField(blank=True, max_length=144, verbose_name='Lapso de pago')),
                ('respons', models.CharField(blank=True, max_length=144)),
                ('status', models.CharField(choices=[('ACTIVE', 'activo'), ('INACTIVE', 'inactivo'), ('BLOCKED', 'bloqueado')], default='INACTIVE', max_length=15, verbose_name='Estado de la cuenta')),
                ('score', models.CharField(choices=[('I', '1'), ('II', '2'), ('III', '3'), ('IV', '4'), ('V', '5'), ('VI', '6')], default='IV', max_length=15, verbose_name='Puntuación')),
                ('role', models.CharField(choices=[('ADMIN', 'admin'), ('SUPERVISOR', 'supervisor'), ('OFFICE', 'oficina'), ('SELLER', 'vendedor'), ('BUYER', 'comprador'), ('PROVIDER', 'proveedor')], default='BUYER', max_length=15, verbose_name='Roles')),
                ('member_since', models.DateTimeField(auto_now_add=True, verbose_name='Miembro desde')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Correo confirmado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
