# Generated by Django 2.1 on 2018-08-24 12:13

from django.db import migrations, models
import src.medias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.ImageField(blank=True, default='/photos/lmp.jpg', null=True, upload_to=src.medias.models.get_upload_path)),
                ('hight', models.ImageField(blank=True, default='/photos/lmp.jpg', null=True, upload_to=src.medias.models.get_upload_path)),
                ('thumb', models.ImageField(blank=True, default='/photos/lmp.jpg', null=True, upload_to=src.medias.models.get_upload_path)),
                ('category', models.CharField(blank=True, max_length=144)),
                ('alt', models.CharField(blank=True, max_length=144)),
                ('position', models.PositiveSmallIntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140)),
                ('url', models.CharField(blank=True, max_length=140)),
                ('alt', models.CharField(blank=True, max_length=140)),
                ('img', models.ImageField(blank=True, default='/videos/lmp.jpg', null=True, upload_to=src.medias.models.get_upload_path)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
