# Generated by Django 2.1 on 2018-08-24 12:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=140)),
                ('milage', models.CharField(blank=True, max_length=140)),
                ('year', models.CharField(blank=True, max_length=140)),
                ('direction', models.CharField(blank=True, max_length=140)),
                ('sub_type', models.CharField(blank=True, max_length=140)),
                ('traction', models.CharField(blank=True, max_length=140)),
                ('transmission', models.CharField(blank=True, max_length=140)),
                ('color', models.CharField(blank=True, max_length=140)),
                ('fuel', models.CharField(blank=True, max_length=140)),
                ('engine', models.CharField(blank=True, max_length=140)),
                ('price', models.CharField(blank=True, max_length=140)),
                ('slug', models.CharField(blank=True, max_length=140)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
                ('photos', models.ManyToManyField(blank=True, to='medias.Photo')),
                ('videos', models.ManyToManyField(blank=True, to='medias.Video')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
    ]
