# Generated by Django 2.1 on 2018-10-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20180824_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand__name'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
    ]
